### ISSUE TITLE
`encodingForModel` method is missing?

### ISSUE THREAD

**Issue by jooy2** [mvitlov/tiktoken#1]
Hello. Thank you for porting `tiktoken` to dart.

I am currently using version 1.0.0.

Maybe this is my mistake, but when I try to use `encodingForModel`, I can't seem to find that method.

```dart
final encoding = encodingForModel("gpt-3.5-turbo");
```

![image](https://user-images.githubusercontent.com/48266008/228098682-48d02be5-66a1-46db-80db-7bc2a8f665de.png)

Is this not implemented yet, or am I using it incorrectly?

Regards,

**Comment by mvitlov** [comment]
@jooy2 Good catch 👍. 
The method was there, but wasn't exposed.

I've just published the new version `1.0.1` that fixes this.

**Comment by jooy2** [comment]
Wow, thank you for the quick response and update!
I upgraded to 1.0.1 and found that `encodingForModel` works fine.

Regards,
