### ISSUE TITLE
Are there plans to support GPT-4 in the future?

### ISSUE THREAD

**Issue by ZingerLittleBee** [mvitlov/tiktoken#2]
I quickly looked through the code and did not find any mention of the GPT-4 model.
Please correct me if I missed anything.
Thank you for your time.

**Comment by mvitlov** [comment]
I've added the support for `GPT-4`. 

The new version `1.0.2` is pushed to [pub.dev](https://pub.dev/packages/tiktoken/versions/1.0.2) also.
